Also configure JUnit to fail on discovery warnings.
If I do this alone without the other changes of this PR, then I get the hoped-for failure:

```
> Task :integrationTestOnJava8 FAILED

JUnit Jupiter > initializationError FAILED
    org.junit.platform.launcher.core.DiscoveryIssueException

1 test completed, 1 failed

> Task :integrationTest FAILED

JUnit Jupiter > initializationError FAILED
    org.junit.platform.launcher.core.DiscoveryIssueException

1 test completed, 1 failed

> Task :integrationTestOnJava9 FAILED

JUnit Jupiter > initializationError FAILED
    org.junit.platform.launcher.core.DiscoveryIssueException

1 test completed, 1 failed

FAILURE: Build completed with 3 failures.
```

And if I combine it with the "actually tell me why things failed" feature, that's:

```
> Task :integrationTestOnJava8 FAILED

JUnit Jupiter > initializationError FAILED
    org.junit.platform.launcher.core.DiscoveryIssueException: TestEngine with ID 'junit-jupiter' encountered 2 critical issues during test discovery:

    (1) [WARNING] @Nested class 'org.jspecify.annotations.NullMarkedTest$WithJava8' must not be static. It will only be executed if discovered as a standalone test class. You should remove the annotation or make it non-static to resolve this warning.
        Source: ClassSource [className = 'org.jspecify.annotations.NullMarkedTest$WithJava8', filePosition = null]
                at org.jspecify.annotations.NullMarkedTest$WithJava8.<no-method>(SourceFile:0)

    (2) [WARNING] @Nested class 'org.jspecify.annotations.NullMarkedTest$WithJava9OrLater' must not be static. It will only be executed if discovered as a standalone test class. You should remove the annotation or make it non-static to resolve this warning.
        Source: ClassSource [className = 'org.jspecify.annotations.NullMarkedTest$WithJava9OrLater', filePosition = null]
                at org.jspecify.annotations.NullMarkedTest$WithJava9OrLater.<no-method>(SourceFile:0)

1 test completed, 1 failed

> Task :integrationTest FAILED

JUnit Jupiter > initializationError FAILED
    org.junit.platform.launcher.core.DiscoveryIssueException: TestEngine with ID 'junit-jupiter' encountered 2 critical issues during test discovery:

    (1) [WARNING] @Nested class 'org.jspecify.annotations.NullMarkedTest$WithJava8' must not be static. It will only be executed if discovered as a standalone test class. You should remove the annotation or make it non-static to resolve this warning.
        Source: ClassSource [className = 'org.jspecify.annotations.NullMarkedTest$WithJava8', filePosition = null]
                at org.jspecify.annotations.NullMarkedTest$WithJava8.<no-method>(SourceFile:0)

    (2) [WARNING] @Nested class 'org.jspecify.annotations.NullMarkedTest$WithJava9OrLater' must not be static. It will only be executed if discovered as a standalone test class. You should remove the annotation or make it non-static to resolve this warning.
        Source: ClassSource [className = 'org.jspecify.annotations.NullMarkedTest$WithJava9OrLater', filePosition = null]
                at org.jspecify.annotations.NullMarkedTest$WithJava9OrLater.<no-method>(SourceFile:0)

1 test completed, 1 failed

> Task :integrationTestOnJava9 FAILED

JUnit Jupiter > initializationError FAILED
    org.junit.platform.launcher.core.DiscoveryIssueException: TestEngine with ID 'junit-jupiter' encountered 2 critical issues during test discovery:

    (1) [WARNING] @Nested class 'org.jspecify.annotations.NullMarkedTest$WithJava8' must not be static. It will only be executed if discovered as a standalone test class. You should remove the annotation or make it non-static to resolve this warning.
        Source: ClassSource [className = 'org.jspecify.annotations.NullMarkedTest$WithJava8', filePosition = null]
                at org.jspecify.annotations.NullMarkedTest$WithJava8.<no-method>(SourceFile:0)

    (2) [WARNING] @Nested class 'org.jspecify.annotations.NullMarkedTest$WithJava9OrLater' must not be static. It will only be executed if discovered as a standalone test class. You should remove the annotation or make it non-static to resolve this warning.
        Source: ClassSource [className = 'org.jspecify.annotations.NullMarkedTest$WithJava9OrLater', filePosition = null]
                at org.jspecify.annotations.NullMarkedTest$WithJava9OrLater.<no-method>(SourceFile:0)

1 test completed, 1 failed
```