Enable more verbose test output, and fix a JUnit warning that it reveals.
This includes displaying stderr+stdout and displaying stack traces.

Once we can see stderr, we see this warning:

`@Nested class 'org.jspecify.annotations.NullMarkedTest$WithJava8' must not be static. It will only be executed if discovered as a standalone test class. You should remove the annotation or make it non-static to resolve this warning.`

You may recall that we can't make the class non-static because of https://github.com/jspecify/jspecify/pull/517.

As best I can tell, there was no need to use nested classes here at all back in https://github.com/jspecify/jspecify/pull/163, and incidentally we can use `@EnabledOnJre`+`@DisabledOnJre`.

This PR was prompted by https://github.com/uber/NullAway/pull/1835. Apparently I could just have looked at [the similar configuration in the reference checker](https://github.com/jspecify/jspecify-reference-checker/commit/9ca43aa9b80db1e7aac69c0331437386bb8f68d5#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R49). I did deviate slightly from that here:
- I didn't carry over `showStackTraces = false`: We didn't need stack traces for failures in the samples because the interesting part there is the line number for the samples, but in a more "normal" project like, they're nice. (At least they add the failure message and full test class's name, though sadly Gradle doesn't trim the stack trace as I would have hoped.)
- I didn't carry over: `events "failed"`: That tells Gradle to output events of the `FAILED` type, but that type that is already displayed by default (along with `STANDARD_OUT` and `STANDARD_ERROR` from the new `showStandardStreams = true`). We could remove `events "failed"` from the reference-checker build, too.

Demo of the before-and-after output for a failure:

```
@NullMarked > onlyBasicReflectionWorksUnderJava8() FAILED
    org.opentest4j.AssertionFailedError at NullMarkedTest.java:53
```

```
@NullMarked > onlyBasicReflectionWorksUnderJava8() FAILED
    org.opentest4j.AssertionFailedError: Expected java.lang.ArrayStoreException to be thrown, but nothing was thrown.
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
        at org.jspecify.annotations.NullMarkedTest.onlyBasicReflectionWorksUnderJava8(NullMarkedTest.java:53)
```